version: '3.8'

services:
  app:
    image: ghcr.io/viniisouzaia/diasgomes-audio-ia:v1.2.1
    networks:
      - diasgomes
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000
      - MAX_UPLOAD_MB=25
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.diasgomes_audio.rule=Host(`transcritor.diasgomesadvoc.com.br`)"
        - "traefik.http.routers.diasgomes_audio.entrypoints=websecure"
        - "traefik.http.routers.diasgomes_audio.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.diasgomes_audio.service=diasgomes_audio"
        - "traefik.http.services.diasgomes_audio.loadbalancer.server.port=3000"
        - "traefik.http.services.diasgomes_audio.loadbalancer.passhostheader=true"

networks:
  diasgomes:
    external: true
